export const initialFlow = {
  conjugations: null,
  inputValue: "",
  inputReq: "",
  showConjugations: false,
  foundVerb: null,
  termination: null,
  termEntrie: null,
  hasTargetCanonical1: null,
  hasTargetCanonical2: null,
  hasTargetAbundance1: null,
  hasTargetAbundance2: null,
  note_plain: null,
  note_ref: null,
  types: null,
  model: null,
  loading: false,
  suggestions: null,
  showButton: false,
  isButtonDisabled: false,
  showSuggestions: false,
  showHome: true,
  showSobre: false,
  showStatistic: false,
  showReviewButton: false,
  goThrough: false,
  enter: false,
  progress: 0,
  isDisabled: false,

  originalVerb: null,
  variationVerb: null,
  result: null,
  findedWord: null,
  similar: null,
  punct: null,

  variations: null,
  varHasVariations: false,
  varProcessedInput: null,
  varForcedVerb: false,
  varPrefixFounded: false,
  varMatchingAfixo: null,
  varConector: null,
  varOriginalInput: null,

  canonical: "canonical1",

  isOnline: null
}

export const pattern = {
  hasTargetCanonical1: false,
  hasTargetCanonical2: false,
  hasTargetAbundance1: false,
  hasTargetAbundance2: false,
  termination: null,
  termEntrie: null,
  verb: null,
  types: null,
  note_plain: null,
  note_ref: null,
  afixo: null,
  model: null
}